name: Test

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y flatpak flatpak-builder
        
      - name: Build
        run: |
            flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
            flatpak install -y --user org.kde.Platform/x86_64/5.15 org.kde.Sdk/x86_64/5.15 
            flatpak-builder --repo=repo --force-clean --install --user build-dir/ info.smplayer.SMPlayer.yml
            flatpak build-bundle repo smplayer.flatpak info.smplayer.SMPlayer

      - name: List
        run: ls -lR build-dir/

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
      
      - name: Create repo artifact
        uses: actions/upload-artifact@v2
        with:
          name: repo
          path: ./repo/

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: smplayer.flatpak
          path: ./smplayer.flatpak
